export const NODE_API_BASE_URL = 'http://localhost:3050/as-api';
export const unregisteredToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjcyYTMyZjAyMzU1NGY4NWI5NWVmZmYiLCJyb2xlIjoidW5yZWdpc3RlcmVkVXNlciIsInRpbWVzdGFtcCI6IjIwMjItMDUtMDhUMTc6MTI6MzUuOTU4WiIsImlhdCI6MTY1MjAyOTk1NSwiZXhwIjoxNjUyNjM0NzU1fQ.Wd-Il9EJ_sZS5slOU99dfKT2Tw4QGi_-fZTShDSJTa8";
